# Generated by Django 3.0.2 on 2020-01-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('parkings', models.IntegerField()),
                ('locality', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pic', models.CharField(max_length=50)),
                ('estate', models.CharField(max_length=50)),
                ('star', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=5)),
                ('phoneNum', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('userLevel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('houseID', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.Housing')),
            ],
        ),
    ]
