# Generated by Django 3.0.2 on 2020-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='locality',
            field=models.CharField(max_length=200),
        ),
    ]
