# Generated by Django 3.0.2 on 2020-01-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20200126_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='kilidUser',
        ),
    ]
