# Generated by Django 3.0.2 on 2020-01-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20200126_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiliduser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kiliduser',
            name='userLevel',
            field=models.BooleanField(default=False),
        ),
    ]
