# Generated by Django 3.0.2 on 2020-01-29 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0006_datauser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dataUser',
        ),
        migrations.AlterModelOptions(
            name='kiliduser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='kiliduser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='kiliduser',
            name='username',
        ),
        migrations.AddField(
            model_name='kiliduser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
