# Generated by Django 3.0.2 on 2020-01-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_auto_20200129_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='housing',
        ),
    ]
