# Generated by Django 3.0.2 on 2020-01-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0010_remove_comment_housing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homeImgs')),
            ],
        ),
        migrations.AlterField(
            model_name='housing',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.Image'),
        ),
    ]
