# Generated by Django 3.0.2 on 2020-01-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0011_auto_20200129_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.Image'),
        ),
    ]
