# Generated by Django 3.0.2 on 2020-01-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0012_auto_20200129_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='pic',
        ),
        migrations.AddField(
            model_name='image',
            name='related_house',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='homes.Housing'),
        ),
    ]
