# Generated by Django 3.0.2 on 2020-01-30 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0013_auto_20200129_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='related_house',
        ),
        migrations.AddField(
            model_name='housing',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.Image'),
        ),
    ]
