# Generated by Django 3.0.2 on 2020-01-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0014_auto_20200130_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
