# Generated by Django 3.0.2 on 2020-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0015_auto_20200130_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
