# Generated by Django 3.0.2 on 2020-01-31 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0020_auto_20200130_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='bookmark',
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='homes.Housing')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='homes.kilidUser')),
            ],
        ),
    ]
