# Generated by Django 3.0.2 on 2020-01-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0021_auto_20200131_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homes.Housing'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homes.kilidUser'),
        ),
    ]
