# Generated by Django 3.0.2 on 2020-01-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0023_auto_20200131_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='pic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
